### PR TITLE
Add Order possibility

### PR DESCRIPTION
**Pull request by ioniks**
And fix problem with null value (on datetime for example)

### CODE REVIEW

**Comment by Webonaute** [comment]
Thank I will review the change as most of the change not complain on the code format I use.

**Comment by Webonaute** [comment]
Change has been added to master and tagged v1.2.1

**Comment by ioniks** [comment]
Why My code is on your git without mentionned my travel or merge with my merge request ?
(you have copied it intregaly ! and made just few change )

**Comment by Webonaute** [comment]
Like I said in the previous comment, you were changing some stuff I cannot merge. Documentation link, Code format. You did not add correct order option validation so I added it. I thank you for your contribution but I could not just merge it like that. I hop you understand.

**Comment by ioniks** [comment]
You can say change for merge before add my code without notifing me .....
So i don't understand why you do it without say to me change what to do before merge

**Comment by Webonaute** [comment]
sorry. I am not very familiar with the github workflow and for the small amount of time I have to maintain this, and a few line of code to implement, I just see it faster to just put the code and not have to do some back and forth to integrate the functionality. I have no bad intention here.

**Comment by Webonaute** [comment]
I added your contribution to the readme file.
Is it ok for you?

**Comment by ioniks** [comment]
yes thanks

**Pull request closed without merging**
