### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by zhil**
Using composer require --dev would allow to skip bundles in production with composer install --no-dev

added it to docs

fixed composer command in docs
fixed default title for Y/N

### CODE REVIEW

**Comment by Webonaute** [comment]
If you use the annotation namespace Webonaute\DoctrineFixturesGeneratorBundle\Annotations\Property in any entities, you can't use it as --dev only.

**Comment by zhil** [comment]
@Webonaute ok, got you. I have removed --dev flag from PR, please check other changes

**Comment by Webonaute** [comment]
The confirmation value will remain false by default. I fixed already the package name in the documentation is the latest version. So this pull request is no longer need. thank you.

**Comment by zhil** [comment]
@Webonaute right now default value and text prompt are not match - Y/n with default false. This is pretty confusing

**Comment by Webonaute** [comment]
ok. I will change only the Y/n for y/N.

**Pull request closed without merging**
